import type { RuntimeScenario } from './scenarioTypes';

export const reportingAccessScenario: RuntimeScenario = {
  id: 'reporting-access',
  label: 'Grant access to reporting app',
  request: {
    title: 'Grant access to reporting app',
    state: 'Paused at human approval before governed execution',
    owner: 'Access Operator',
    risk: 'medium',
    autonomyMode: 'human-approved execution',
  },
  trustModel: {
    level: 'Moderate',
    currentBoundary: 'Delegation mode: Human-approved execution · Execution mode: Prepared only',
    delegationRule: 'The runtime may prepare the tool call, but it may not issue any write action before human approval.',
    downgradeRule: 'If verification fails or the approval is denied, the workflow remains human-controlled and execution authority is removed.',
  },
  operators: [
    {
      agentId: 'intake',
      name: 'Intake Bot',
      kind: 'intake-agent',
      lane: 'intake',
      runtime: 'nemoclaw',
      workspace: '~/.openclaw/workspaces/intake-bot',
      sessionType: 'persistent',
      authorityProfile: 'clarify_and_route_only',
      allowedSubstrates: ['openclaw-routing'],
      status: 'completed_handoff',
    },
    {
      agentId: 'access-operator',
      name: 'Access Operator',
      kind: 'operator-agent',
      lane: 'access',
      runtime: 'nemoclaw',
      workspace: '~/.openclaw/workspaces/access-operator',
      sessionType: 'persistent',
      authorityProfile: 'bounded_access_changes',
      allowedSubstrates: ['openclaw-tools', 'openshell'],
      status: 'active',
    },
    {
      agentId: 'duty-operator',
      name: 'Duty Operator',
      kind: 'human-approver',
      lane: 'approval',
      runtime: 'nemoclaw',
      workspace: null,
      sessionType: 'on-demand',
      authorityProfile: 'approval_and_override',
      allowedSubstrates: ['trustplane-controls'],
      status: 'pending_approval',
    },
  ],
  ownership: {
    currentOwner: {
      actorType: 'operator-agent',
      agentId: 'access-operator',
      name: 'Access Operator',
      lane: 'access',
    },
    previousOwner: {
      actorType: 'intake-agent',
      agentId: 'intake',
      name: 'Intake Bot',
      lane: 'intake',
    },
    assignedAt: '10:02',
    ownershipReason: 'NemoClaw routing matched normalized access_request intake to the access lane and handed ownership to Access Operator.',
  },
  delegation: {
    delegationMode: 'automatic',
    routingComponent: 'nemoclaw-request-router',
    selectedLane: 'access',
    selectedAgentId: 'access-operator',
    candidateLanes: ['access'],
    rejectedLanes: ['endpoint', 'change'],
    reason: 'The request is complete, the target system is reporting, and the workflow maps cleanly to the access operator lane.',
    confidence: 'high',
    humanConfirmationRequired: false,
  },
  authorityBoundary: {
    agentId: 'access-operator',
    authorityMode: 'prepare_and_execute_with_approval',
    mayClarify: false,
    mayPrepare: true,
    mayExecute: true,
    mayApprove: false,
    mayDelegate: false,
    requiresHumanApprovalBeforeExecution: true,
    separationOfDutiesRule: 'Sensitive access requests cannot be self-approved by the owning operator agent.',
  },
  executionSubstrate: {
    substrateId: 'openclaw-tools',
    substrateKind: 'openclaw-tools',
    displayName: 'OpenClaw Governed Tools',
    mode: 'prepared_only_until_approval',
    supportsStreaming: true,
    supportsVerificationArtifacts: true,
  },
  stages: [],
  humanCheckpoints: [],
  executionSteps: [],
  timeline: [],
  inspections: {},
  playbook: {
    name: 'analytics-read-standard',
    trigger: 'Standard request for reporting read access',
    preconditions: [
      'Target app is registered in the access catalog',
      'Requester role is recognized',
      'Requested entitlement is within approved reporting scope',
    ],
    allowedTools: ['reporting-access.grant', 'directory.lookup', 'access.verify'],
    approvalRequirement: 'Required for governed reporting datasets before any write action.',
    rollback: 'Remove entitlement, run verification again, and attach rollback artifact.',
  },
};
