import type { RuntimeScenario } from './scenarioTypes';

export const reportingAccessScenario: RuntimeScenario = {
  id: 'reporting-access',
  label: 'Grant access to reporting app',
  request: {
    title: 'Grant access to reporting app',
    state: 'Paused at human approval before governed execution',
    owner: 'Access Operator',
    risk: 'medium',
    autonomyMode: 'human-approved execution',
  },
  trustModel: {
    level: 'Moderate',
    currentBoundary: 'Delegation mode: Human-approved execution · Execution mode: Prepared only',
    delegationRule: 'The runtime may prepare the tool call, but it may not issue any write action before human approval.',
    downgradeRule: 'If verification fails or the approval is denied, the workflow remains human-controlled and execution authority is removed.',
  },
  operators: [],
  ownership: {
    currentOwner: { actorType: 'operator-agent', agentId: 'access-operator', name: 'Access Operator', lane: 'access' },
    previousOwner: { actorType: 'intake-agent', agentId: 'intake', name: 'Intake Agent', lane: 'intake' },
    assignedAt: '10:02',
    ownershipReason: 'OpenClaw routing matched normalized access_request intake to the access lane.',
  },
  delegation: {
    delegationMode: 'automatic',
    routingComponent: 'openclaw-request-router',
    selectedLane: 'access',
    selectedAgentId: 'access-operator',
    candidateLanes: ['access'],
    rejectedLanes: [],
    reason: 'The request maps cleanly to the access operator lane.',
    confidence: 'high',
    humanConfirmationRequired: false,
  },
  authorityBoundary: {
    agentId: 'access-operator',
    authorityMode: 'prepare_and_execute_with_approval',
    mayClarify: false,
    mayPrepare: true,
    mayExecute: true,
    mayApprove: false,
    mayDelegate: false,
    requiresHumanApprovalBeforeExecution: true,
    separationOfDutiesRule: 'Sensitive access requests cannot be self-approved by the owning operator agent.',
  },
  executionSubstrate: {
    substrateId: 'openclaw-tools',
    substrateKind: 'openclaw-tools',
    displayName: 'OpenClaw Governed Tools',
    mode: 'prepared_only_until_approval',
    supportsStreaming: true,
    supportsVerificationArtifacts: true,
  },
  commandEnvelope: {
    preparedByAgentId: 'access-operator',
    intendedExecutor: { actorType: 'operator-agent', agentId: 'access-operator', name: 'Access Operator' },
    substrateId: 'openclaw-tools',
    command: 'reporting-access.grant analyst@company reporting.read',
    arguments: ['analyst@company', 'reporting.read'],
    workingDirectory: '/opt/trustplane/runtime/access-operator',
    riskClass: 'medium',
    approvalState: 'pending',
    rollbackCommand: 'reporting-access.revoke analyst@company reporting.read',
    expectedVerification: 'readback_and_compare',
  },
  stages: [],
  humanCheckpoints: [],
  executionSteps: [],
  timeline: [],
  inspections: {},
  playbook: {
    name: 'analytics-read-standard',
    trigger: 'Standard request for reporting read access',
    preconditions: [],
    allowedTools: ['reporting-access.grant', 'directory.lookup', 'access.verify'],
    approvalRequirement: 'Required for governed reporting datasets before any write action.',
    rollback: 'Remove entitlement, run verification again, and attach rollback artifact.',
  },
};
