import type { RuntimeScenario } from './scenarioTypes';

export const vpnPolicyScenario: RuntimeScenario = {
  id: 'vpn-policy-change',
  label: 'Change VPN access policy',
  request: {
    title: 'Change VPN access policy',
    state: 'Awaiting operator-agent execution release',
    owner: 'Change Operator',
    risk: 'high',
    autonomyMode: 'operator-agent execution after approval',
  },
  trustModel: {
    level: 'Moderate',
    currentBoundary: 'Delegation mode: Human-approved operator-agent execution · Execution mode: Prepared in OpenShell',
    delegationRule: 'The change operator may stage the exact change and rollback envelope, but it may not execute through OpenShell until approval releases authority.',
    downgradeRule: 'If verification fails or review rejects the staged change, the operator agent loses execution authority and the envelope is invalidated.',
  },
  operators: [
    {
      agentId: 'intake',
      name: 'Intake Bot',
      kind: 'intake-agent',
      lane: 'intake',
      runtime: 'nemoclaw',
      workspace: '~/.openclaw/workspaces/intake-bot',
      sessionType: 'persistent',
      authorityProfile: 'clarify_and_route_only',
      allowedSubstrates: ['openclaw-routing'],
      status: 'completed_handoff',
    },
    {
      agentId: 'change-operator',
      name: 'Change Operator',
      kind: 'operator-agent',
      lane: 'change',
      runtime: 'nemoclaw',
      workspace: '~/.openclaw/workspaces/change-operator',
      sessionType: 'persistent',
      authorityProfile: 'prepare_high_risk_change_and_execute_after_release',
      allowedSubstrates: ['openshell'],
      status: 'awaiting_execution_release',
    },
    {
      agentId: 'duty-operator',
      name: 'Duty Operator',
      kind: 'human-approver',
      lane: 'approval',
      runtime: 'nemoclaw',
      workspace: null,
      sessionType: 'on-demand',
      authorityProfile: 'approval_and_override',
      allowedSubstrates: ['trustplane-controls'],
      status: 'approved',
    },
  ],
  ownership: {
    currentOwner: {
      actorType: 'operator-agent',
      agentId: 'change-operator',
      name: 'Change Operator',
      lane: 'change',
    },
    previousOwner: {
      actorType: 'intake-agent',
      agentId: 'intake',
      name: 'Intake Bot',
      lane: 'intake',
    },
    assignedAt: '18:21',
    ownershipReason: 'NemoClaw routing matched the normalized infrastructure_change request to the change operator lane.',
  },
  delegation: {
    delegationMode: 'automatic',
    routingComponent: 'nemoclaw-request-router',
    selectedLane: 'change',
    selectedAgentId: 'change-operator',
    candidateLanes: ['change'],
    rejectedLanes: ['access', 'endpoint'],
    reason: 'The target system is vpn-policy and the request implies a governed infrastructure change with rollback planning.',
    confidence: 'high',
    humanConfirmationRequired: false,
  },
  authorityBoundary: {
    agentId: 'change-operator',
    authorityMode: 'prepare_then_execute_after_human_release',
    mayClarify: false,
    mayPrepare: true,
    mayExecute: true,
    mayApprove: false,
    mayDelegate: false,
    requiresHumanApprovalBeforeExecution: true,
    separationOfDutiesRule: 'High-risk policy changes require human approval before a change operator may execute through OpenShell.',
  },
  executionSubstrate: {
    substrateId: 'openshell',
    substrateKind: 'command-runtime',
    displayName: 'NVIDIA OpenShell',
    mode: 'prepared_for_operator_agent_execution',
    supportsStreaming: true,
    supportsVerificationArtifacts: true,
  },
  stages: [],
  humanCheckpoints: [],
  executionSteps: [],
  timeline: [],
  inspections: {},
  playbook: {
    name: 'vpn-policy-standard-change',
    trigger: 'Standard VPN policy modification during approved maintenance window',
    preconditions: [
      'Maintenance window is active',
      'Requested policy scope is bounded',
      'Rollback payload has been generated',
    ],
    allowedTools: ['vpn-policy.read', 'vpn-policy.update', 'vpn-policy.verify'],
    approvalRequirement: 'Approval required before operator-agent execution release.',
    rollback: 'Apply rollback payload, verify policy convergence, and attach rollback artifact.',
  },
};
