import type { RuntimeScenario } from './scenarioTypes';

export const vpnPolicyScenario: RuntimeScenario = {
  id: 'vpn-policy-change',
  label: 'Change VPN access policy',
  request: {
    title: 'Change VPN access policy',
    state: 'Awaiting operator-agent execution release',
    owner: 'Change Operator',
    risk: 'high',
    autonomyMode: 'operator-agent execution after approval',
  },
  trustModel: {
    level: 'Moderate',
    currentBoundary: 'Delegation mode: Human-approved operator-agent execution · Execution mode: Prepared in OpenShell',
    delegationRule: 'The change operator may stage the exact change and rollback envelope, but it may not execute through OpenShell until approval releases authority.',
    downgradeRule: 'If verification fails or review rejects the staged change, the operator agent loses execution authority and the envelope is invalidated.',
  },
  operators: [],
  ownership: {
    currentOwner: { actorType: 'operator-agent', agentId: 'change-operator', name: 'Change Operator', lane: 'change' },
    previousOwner: { actorType: 'intake-agent', agentId: 'intake', name: 'Intake Agent', lane: 'intake' },
    assignedAt: '18:21',
    ownershipReason: 'OpenClaw routing matched the normalized infrastructure_change request to the change operator lane.',
  },
  delegation: {
    delegationMode: 'automatic',
    routingComponent: 'openclaw-request-router',
    selectedLane: 'change',
    selectedAgentId: 'change-operator',
    candidateLanes: ['change'],
    rejectedLanes: [],
    reason: 'The target system is vpn-policy and the request implies a governed infrastructure change.',
    confidence: 'high',
    humanConfirmationRequired: false,
  },
  authorityBoundary: {
    agentId: 'change-operator',
    authorityMode: 'prepare_then_execute_after_human_release',
    mayClarify: false,
    mayPrepare: true,
    mayExecute: true,
    mayApprove: false,
    mayDelegate: false,
    requiresHumanApprovalBeforeExecution: true,
    separationOfDutiesRule: 'High-risk policy changes require human approval before a change operator may execute through OpenShell.',
  },
  executionSubstrate: {
    substrateId: 'openshell',
    substrateKind: 'command-runtime',
    displayName: 'NVIDIA OpenShell',
    mode: 'prepared_for_operator_agent_execution',
    supportsStreaming: true,
    supportsVerificationArtifacts: true,
  },
  commandEnvelope: {
    preparedByAgentId: 'change-operator',
    intendedExecutor: { actorType: 'operator-agent', agentId: 'change-operator', name: 'Change Operator' },
    substrateId: 'openshell',
    command: 'vpn-policy update --profile vendor-nightly --allow 203.0.113.10/32',
    arguments: ['update', '--profile', 'vendor-nightly', '--allow', '203.0.113.10/32'],
    workingDirectory: '/opt/trustplane/runtime/change-operator',
    riskClass: 'high',
    approvalState: 'released',
    rollbackCommand: 'vpn-policy rollback --profile vendor-nightly',
    expectedVerification: 'policy_readback_matches_staged_diff',
  },
  stages: [],
  humanCheckpoints: [],
  executionSteps: [],
  timeline: [],
  inspections: {},
  playbook: {
    name: 'vpn-policy-standard-change',
    trigger: 'Standard VPN policy modification during approved maintenance window',
    preconditions: [],
    allowedTools: ['vpn-policy.read', 'vpn-policy.update', 'vpn-policy.verify'],
    approvalRequirement: 'Approval required before operator-agent execution release.',
    rollback: 'Apply rollback payload, verify policy convergence, and attach rollback artifact.',
  },
};
